---
- name: Allow port 51820
  community.general.ufw:
    rule: allow
    port: 51820
    proto: udp
- name: Allow port 5000
  community.general.ufw:
    rule: allow
    port: 5000
    proto: tcp  
- name: Allow port 22
  community.general.ufw:
    rule: allow
    port: 22
    proto: tcp
- name: Allow port 5000
  community.general.ufw:
    rule: allow
    name: OpenSSH
- name: Enable UFW
  community.general.ufw:
    state: enabled